### ISSUE TITLE
Starting project with a running cluster does not return meaningful message

### ISSUE THREAD

**Issue by vvvityaaa** [unikubehq/cli#123]
After starting one project, when I start another project with the same name, but which belongs to another organization, I get an ArgumentError.

![Screenshot from 2021-09-02 09-49-46](https://user-images.githubusercontent.com/10248144/131804500-a9ecfc19-16b1-4006-80de-c3a64c02e113.png)

**Comment by Schille** [comment]
Wow. I thought this would be a super-edge-case. :smiley:

**Comment by buschNT** [comment]
The problem here is that the list displaying function filters out one duplicate, because one project with the name "buzzword-counter" is already up. It therefore does not realize any duplicates and does't include the ID. But then it cannot resolve the project name, since it is not unique.

The "exclude" argument in the `console.project_list` is not implemented properly.
Nice catch.

Furthermore, an exception should not be thrown anyway.

**Comment by buschNT** [comment]
Doku: `project_list(filter=...)` "filter" argument has the same flaw.
