### ISSUE TITLE
cli command: deck -> uninstall

### ISSUE THREAD

**Issue by buschNT** [unikubehq/cli#5]
Not implemented: `unikube deck uninstall`

**Comment by buschNT** [comment]
@Schille How do we want to "uninstall" decks? Is this equivalent to `kubectl delete -f ....`.
Currently we do not save the applied file which we get from the manifest service. Thus I am not sure what happens if the manifest service provides a different file after running `deck install`. Is it then still possible to uninstall it?

**Comment by Schille** [comment]
At the moment, delete from manifest files seems to be the most robust solution (even if there is so leftover in case resources have been removed from the current set of manifests). Deleting any resource in Kubernetes can be done using the manifest file used to create it. With the manifest file we can use the `kubectl delete` with `-f` flag.
1) pull the manifests from the platform (same as install) see https://github.com/unikubehq/cli/blob/main/src/cli/deck.py#L331-L334
2) instead of `apply -f [file]`, we run `delete -f [file]` see https://github.com/unikubehq/cli/blob/14d66640c5ef156b6081a871b7ffda5c36ed3faf/src/local/system.py#L87-L89
