### ISSUE TITLE
Inconsistent behaviour and unhandled errors when deck is given directly

### ISSUE THREAD

**Issue by schwobaseggl** [unikubehq/cli#96]
### Install/Use unknown deck

`unik deck install ventariadapter`
`unik deck use ventariadapter`

raise unhandled exceptions (with or without set project context). This should probably be a more user-friendly message.

### Install known deck without project context

`unik deck install ventari-adapter`

works. How about deck name collisions with other projects. What's the logic there?

### Use known deck without project context

`unik deck use ventari-adapter`

raises unhandled exception (unlike `install`). Why?

**Comment by vvvityaaa** [comment]
Thanks for reporting this bug. Indeed, there was a bug, which led to user-unfriendly exception messages for `install` and `use` commands.
On the other hand, for the `use`-command you currently need to specify ID as selection option, so `unikube deck use ventari-adapter` wouldn't work anyway, as you specify title/name of the deck here and not ID. This is inconsistent with other commands, that's why I started this discussion #98.

**Comment by buschNT** [comment]
Closed by #117 . Context  has been improved.
